trigger:
  - master
pool:
  vmImage: "ubuntu-latest"
variables:
  workingDirectory: "$(System.DefaultWorkingDirectory)/shaun-pearson.dev"
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"
    displayName: "Install Node.js"
  - script: |
      npm install -g gatsby-cli
    displayName: "Install gatsby-cli"
  - script: |
      npm install
    workingDirectory: $(workingDirectory)
    displayName: "Install dependencies"
  - script: |
      npm build
    workingDirectory: $(workingDirectory)
    displayName: "Gatsby build"
  - publish: "$(workingDirectory)/public"
    artifact: website