on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run a build step here if your project requires

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install Project Dependencies
        run: npm ci
        working-directory: ./shaun-pearson.dev
        env: # Or as an environment variable
          TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}

      
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@5.7.0

      - name: Build
        run: gatsby build
        working-directory: ./shaun-pearson.dev

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 53ca29d6e91af4cbcb034ffc8ced93b1
          projectName: bigwhitesolutions
          directory: public
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./shaun-pearson.dev

